server:
  port: 10061
spring:
  application:
    name: gate-way
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
      - id: auth
        uri: lb://server-auth
        predicates:
          - Path=/auth/**
        filters:
          - AuthGatewayFilter
          - StripPrefix=1
      - id: account
        uri: lb://server-account
        predicates:
          - Path=/account/**
        filters:
          - AuthGatewayFilter
          - StripPrefix=1
      - id: cart
        uri: lb://server-cart
        predicates:
          - Path=/cart/**
        filters:
          - AuthGatewayFilter
          - StripPrefix=1
      - id: message
        uri: lb://server-message
        predicates:
          - Path=/message/**
        filters:
          - AuthGatewayFilter
          - StripPrefix=1      - id: martquery
        uri: lb://server-martquery
        predicates:
          - Path=/martquery/**
        filters:
          - AuthGatewayFilter
          - StripPrefix=1
      - id: order
        uri: lb://server-order
        predicates:
          - Path=/order/**
        filters:
          - AuthGatewayFilter
          - StripPrefix=1
      - id: purchase
        uri: lb://server-purchase
        predicates:
          - Path=/purchase/**
        filters:
          - AuthGatewayFilter
          - StripPrefix=1
      - id: seller
        uri: lb://server-seller
        predicates:
          - Path=/seller/**
        filters:
          - AuthGatewayFilter
          - StripPrefix=1
eureka:
  client:
    registryFetchIntervalSeconds: 5
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:10060/eureka
  instance:
    preferIpAddress: true
    hostname: localhost