server:
  port: 10061
spring:
  application:
    name: gate-way
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:      - id: mart
        uri: lb://SERVER-MART
        predicates:
          - Path=/mart/**
        filters:
          - AuthGatewayFilter
          - StripPrefix=1
      - id: auth
        uri: lb://SERVER-AUTH
        predicates:
          - Path=/auth/**
        filters:
          - AuthGatewayFilter
          - StripPrefix=1
eureka:
  client:
    registryFetchIntervalSeconds: 5
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:10060/eureka
  instance:
    preferIpAddress: true
    hostname: localhost