pipeline {
   agent {
        docker { image 'node:7-alpine' }
    }
   
   stages {
      stage('pull code') {
         steps {
            checkout([$class: 'GitSCM', branches: [[name: "*/${branch}"]], doGenerateSubmoduleConfigurations: false, extensions: [], submoduleCfg: [], userRemoteConfigs: [[url: 'https://github.com/Shosetsu/FSD-assignment.git']]])
         }
      }
      stage('build') {
        steps {
            sh "mvn -f emart-microservice/pom.xml clean package -Dmaven.test.skip=true"
        }
      }
      stage('create docker image') {
        steps {
            echo 'TODO create docker image'
        }
      }
      stage('deploy') {
        steps {
            echo 'TODO push to docker hub'
        }
      }
   }
}
