server:
  port: 10052
spring:
  application:
    name: server-purchase
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:10047/emart_a?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: Qwer1234
  jpa:
    database: MYSQL
    show-sql: true